"""
Generate 30 hand-labelled golden calibration cases for the isotonic trust calibrator.

Each case is a realistic legal-document QA scenario with:
  - raw_score: computed from the trust formula
      0.45 * frac_supported + 0.25 * margin_norm + 0.20 * min_rerank + 0.10 * agreement
  - is_correct: ground-truth label (was the answer faithful to the source?)
  - Metadata fields for auditing (ignored by fit_calibrator.py).

Coverage design:
  Cases 001-008  High trust, correct  (raw 0.77-0.97)
  Cases 009-016  Medium-high trust, mostly correct  (raw 0.51-0.87)
  Cases 017-023  Medium-low trust, mostly incorrect  (raw 0.28-0.46)
  Cases 024-030  Low trust, incorrect  (raw 0.04-0.25)
"""
from __future__ import annotations

import json
from pathlib import Path

OUT_DIR = Path(__file__).parent.parent / "services/eval/golden/cases"


def _raw(frac: float, margin_norm: float, min_rerank: float, agreement: float) -> float:
    raw = 0.45 * frac + 0.25 * margin_norm + 0.20 * min_rerank + 0.10 * agreement
    return round(max(0.0, min(1.0, raw)), 4)


CASES = [
    # ── Tier 1: High trust, answer is correct ─────────────────────────────────
    {
        "id": "001",
        "scenario": "Renewal term directly stated",
        "claim": "The agreement auto-renews for 12 months unless cancelled in writing 60 days before expiry.",
        "evidence_snippet": "This Agreement shall automatically renew for successive one-year terms unless either party provides written notice of non-renewal at least sixty (60) days prior to the end of the then-current term.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 1.0,
        "margin_norm": 0.95,
        "min_rerank": 0.92,
        "agreement": 1.0,
        "is_correct": True,
    },
    {
        "id": "002",
        "scenario": "Payment due date explicitly stated",
        "claim": "Payment is due within 30 days of the invoice date.",
        "evidence_snippet": "Customer shall pay each invoice within thirty (30) days of the invoice date. Late payments accrue interest at 1.5% per month.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 1.0,
        "margin_norm": 0.90,
        "min_rerank": 0.88,
        "agreement": 1.0,
        "is_correct": True,
    },
    {
        "id": "003",
        "scenario": "Governing law jurisdiction explicit",
        "claim": "The governing law for this agreement is New York State.",
        "evidence_snippet": "This Agreement shall be governed by and construed in accordance with the laws of the State of New York, without regard to conflict of law principles.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 1.0,
        "margin_norm": 0.85,
        "min_rerank": 0.85,
        "agreement": 1.0,
        "is_correct": True,
    },
    {
        "id": "004",
        "scenario": "Termination notice period clearly stated",
        "claim": "Either party may terminate with 60 days written notice.",
        "evidence_snippet": "Either party may terminate this Agreement for convenience upon sixty (60) days' prior written notice to the other party.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 1.0,
        "margin_norm": 0.80,
        "min_rerank": 0.80,
        "agreement": 1.0,
        "is_correct": True,
    },
    {
        "id": "005",
        "scenario": "Liability cap stated with most claims supported",
        "claim": "The aggregate liability of either party is capped at 2x the annual fees paid in the prior 12 months.",
        "evidence_snippet": "In no event shall either party's liability exceed two times (2x) the total fees paid by Customer in the twelve-month period preceding the claim.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 0.80,
        "margin_norm": 0.85,
        "min_rerank": 0.82,
        "agreement": 0.80,
        "is_correct": True,
    },
    {
        "id": "006",
        "scenario": "Confidentiality survival clause",
        "claim": "Confidentiality obligations survive termination for three years.",
        "evidence_snippet": "The confidentiality obligations set forth in this Section shall survive the expiration or termination of this Agreement for a period of three (3) years.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 1.0,
        "margin_norm": 0.75,
        "min_rerank": 0.78,
        "agreement": 1.0,
        "is_correct": True,
    },
    {
        "id": "007",
        "scenario": "SLA commitment in multi-claim answer",
        "claim": "The vendor guarantees 99.9% monthly uptime for the production service.",
        "evidence_snippet": "Provider guarantees a monthly uptime percentage of 99.9% for the Production Environment, measured over each calendar month.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 0.75,
        "margin_norm": 0.80,
        "min_rerank": 0.78,
        "agreement": 0.75,
        "is_correct": True,
    },
    {
        "id": "008",
        "scenario": "Effective date clearly stated",
        "claim": "The agreement is effective from January 1, 2024.",
        "evidence_snippet": "This Agreement is entered into as of January 1, 2024 (the 'Effective Date').",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 1.0,
        "margin_norm": 0.65,
        "min_rerank": 0.70,
        "agreement": 1.0,
        "is_correct": True,
    },
    # ── Tier 2: Medium-high trust, mostly correct ──────────────────────────────
    {
        "id": "009",
        "scenario": "Indemnification scope partially supported",
        "claim": "Vendor indemnifies Customer against third-party IP infringement claims.",
        "evidence_snippet": "Vendor shall defend and indemnify Customer against any third-party claim alleging that the Software infringes any patent, copyright, or trade secret.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 0.67,
        "margin_norm": 0.70,
        "min_rerank": 0.72,
        "agreement": 0.67,
        "is_correct": True,
    },
    {
        "id": "010",
        "scenario": "Assignment clause inferred correctly",
        "claim": "Neither party may assign this agreement without the other's prior written consent.",
        "evidence_snippet": "Neither party may assign or transfer any of its rights or obligations hereunder without the prior written consent of the other party, not to be unreasonably withheld.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 0.50,
        "margin_norm": 0.75,
        "min_rerank": 0.68,
        "agreement": 0.50,
        "is_correct": True,
    },
    {
        "id": "011",
        "scenario": "Price increase cap correctly identified",
        "claim": "Annual price increases are limited to 5% above the prior year's fees.",
        "evidence_snippet": "Provider may increase fees upon renewal, provided that any increase does not exceed five percent (5%) above the fees applicable in the immediately preceding contract year.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 0.75,
        "margin_norm": 0.55,
        "min_rerank": 0.65,
        "agreement": 0.75,
        "is_correct": True,
    },
    {
        "id": "012",
        "scenario": "Assignment clause — answer is subtly wrong (exception missed)",
        "claim": "Parties may freely assign this agreement to affiliates without consent.",
        "evidence_snippet": "Neither party may assign or transfer any of its rights or obligations hereunder without the prior written consent of the other party, not to be unreasonably withheld.",
        "critic_verdict": "supported",
        "nli_label": "neutral",
        "frac_supported": 0.50,
        "margin_norm": 0.65,
        "min_rerank": 0.60,
        "agreement": 0.50,
        "is_correct": False,
    },
    {
        "id": "013",
        "scenario": "Force majeure correctly identified",
        "claim": "Force majeure events excuse performance obligations except for payment.",
        "evidence_snippet": "Neither party shall be liable for failure to perform due to causes beyond its reasonable control (force majeure), provided that payment obligations are expressly excluded from this provision.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 0.67,
        "margin_norm": 0.50,
        "min_rerank": 0.55,
        "agreement": 0.67,
        "is_correct": True,
    },
    {
        "id": "014",
        "scenario": "Dispute resolution — venue inferred incorrectly",
        "claim": "All disputes must be resolved by arbitration in New York City.",
        "evidence_snippet": "Any dispute arising under this Agreement shall be resolved through binding arbitration administered by the AAA under its Commercial Rules.",
        "critic_verdict": "supported",
        "nli_label": "neutral",
        "frac_supported": 0.33,
        "margin_norm": 0.70,
        "min_rerank": 0.60,
        "agreement": 0.33,
        "is_correct": False,
    },
    {
        "id": "015",
        "scenario": "Borderline: work-for-hire partially supported",
        "claim": "All custom work product developed under the agreement belongs to Customer.",
        "evidence_snippet": "Any custom deliverables specifically developed for Customer under a Statement of Work shall be considered works made for hire, with ownership vesting in Customer upon payment in full.",
        "critic_verdict": "supported",
        "nli_label": "neutral",
        "frac_supported": 0.50,
        "margin_norm": 0.50,
        "min_rerank": 0.55,
        "agreement": 0.50,
        "is_correct": True,
    },
    {
        "id": "016",
        "scenario": "Insurance requirement correctly stated",
        "claim": "Vendor must maintain commercial general liability insurance of at least $2M per occurrence.",
        "evidence_snippet": "Provider shall maintain, at its expense, commercial general liability insurance with coverage of not less than $2,000,000 per occurrence and $5,000,000 in the aggregate.",
        "critic_verdict": "supported",
        "nli_label": "entail",
        "frac_supported": 1.0,
        "margin_norm": 0.55,
        "min_rerank": 0.60,
        "agreement": 1.0,
        "is_correct": True,
    },
    # ── Tier 3: Medium-low trust, mostly incorrect ─────────────────────────────
    {
        "id": "017",
        "scenario": "Warranty period overstated",
        "claim": "The software warranty period is 90 days from delivery.",
        "evidence_snippet": "Provider warrants that the Software will perform materially in accordance with the Documentation for a period of thirty (30) days following delivery.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.25,
        "margin_norm": 0.60,
        "min_rerank": 0.55,
        "agreement": 0.25,
        "is_correct": False,
    },
    {
        "id": "018",
        "scenario": "Auto-termination not in contract",
        "claim": "The agreement automatically terminates after five years with no renewal.",
        "evidence_snippet": "This Agreement shall have an initial term of one (1) year from the Effective Date and shall automatically renew for successive one-year terms unless terminated.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.33,
        "margin_norm": 0.45,
        "min_rerank": 0.50,
        "agreement": 0.33,
        "is_correct": False,
    },
    {
        "id": "019",
        "scenario": "Cost allocation answer is wrong",
        "claim": "Customer bears all infrastructure and hosting costs under the agreement.",
        "evidence_snippet": "Provider is responsible for all infrastructure, hosting, and maintenance costs required to operate the service as described in the applicable Order Form.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.50,
        "margin_norm": 0.35,
        "min_rerank": 0.45,
        "agreement": 0.50,
        "is_correct": False,
    },
    {
        "id": "020",
        "scenario": "Termination fee scope overstated",
        "claim": "A termination fee equal to 6 months of remaining fees applies on any early termination.",
        "evidence_snippet": "In the event Customer terminates for convenience prior to the end of a term, Customer shall pay a termination fee equal to six (6) months of the then-applicable monthly fees.",
        "critic_verdict": "unsupported",
        "nli_label": "neutral",
        "frac_supported": 0.25,
        "margin_norm": 0.40,
        "min_rerank": 0.45,
        "agreement": 0.25,
        "is_correct": False,
    },
    {
        "id": "021",
        "scenario": "IP ownership stated backwards",
        "claim": "The contractor retains full ownership of all work product created under this agreement.",
        "evidence_snippet": "All deliverables, work product, and intellectual property created by Provider specifically for Customer shall be owned exclusively by Customer.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.33,
        "margin_norm": 0.35,
        "min_rerank": 0.40,
        "agreement": 0.33,
        "is_correct": False,
    },
    {
        "id": "022",
        "scenario": "Non-compete scope overstated",
        "claim": "The non-compete clause restricts the contractor from working in any market globally for 2 years.",
        "evidence_snippet": "For a period of two (2) years following termination, Contractor shall not engage in competitive activities within the United States in the specific vertical markets listed in Schedule A.",
        "critic_verdict": "unsupported",
        "nli_label": "neutral",
        "frac_supported": 0.25,
        "margin_norm": 0.30,
        "min_rerank": 0.42,
        "agreement": 0.25,
        "is_correct": False,
    },
    {
        "id": "023",
        "scenario": "Insurance amount not in evidence",
        "claim": "Vendor must carry $5M in errors and omissions insurance.",
        "evidence_snippet": "Provider shall maintain professional liability (errors and omissions) insurance in such amounts as are customary for providers of similar services.",
        "critic_verdict": "unsupported",
        "nli_label": "neutral",
        "frac_supported": 0.00,
        "margin_norm": 0.65,
        "min_rerank": 0.60,
        "agreement": 0.00,
        "is_correct": False,
    },
    # ── Tier 4: Low trust, answer is incorrect ─────────────────────────────────
    {
        "id": "024",
        "scenario": "Interest rate fabricated",
        "claim": "Late payments accrue interest at 3% per month.",
        "evidence_snippet": "Late payments shall accrue interest at the rate of one and one-half percent (1.5%) per month.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.00,
        "margin_norm": 0.20,
        "min_rerank": 0.30,
        "agreement": 0.00,
        "is_correct": False,
    },
    {
        "id": "025",
        "scenario": "Governing law stated incorrectly",
        "claim": "This agreement is governed by California law.",
        "evidence_snippet": "This Agreement shall be governed by and construed in accordance with the laws of the State of New York.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.00,
        "margin_norm": 0.15,
        "min_rerank": 0.25,
        "agreement": 0.00,
        "is_correct": False,
    },
    {
        "id": "026",
        "scenario": "Notice period understated",
        "claim": "Termination requires only 14 days notice.",
        "evidence_snippet": "Either party may terminate this Agreement for convenience upon sixty (60) days' prior written notice to the other party.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.00,
        "margin_norm": 0.10,
        "min_rerank": 0.20,
        "agreement": 0.00,
        "is_correct": False,
    },
    {
        "id": "027",
        "scenario": "Liability stated as uncapped",
        "claim": "There is no cap on the liability of either party under this agreement.",
        "evidence_snippet": "In no event shall either party's aggregate liability exceed five hundred thousand dollars ($500,000).",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.00,
        "margin_norm": 0.05,
        "min_rerank": 0.15,
        "agreement": 0.00,
        "is_correct": False,
    },
    {
        "id": "028",
        "scenario": "Renewal described as not automatic",
        "claim": "The agreement does not auto-renew; a new order must be placed each year.",
        "evidence_snippet": "Unless either party provides written notice of non-renewal at least sixty (60) days prior to expiry, the Agreement shall automatically renew for successive one-year terms.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.00,
        "margin_norm": 0.30,
        "min_rerank": 0.35,
        "agreement": 0.00,
        "is_correct": False,
    },
    {
        "id": "029",
        "scenario": "Confidentiality duration understated",
        "claim": "Confidentiality obligations last only one year after termination.",
        "evidence_snippet": "The confidentiality obligations shall survive the expiration or termination of this Agreement for a period of three (3) years.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.25,
        "margin_norm": 0.20,
        "min_rerank": 0.30,
        "agreement": 0.25,
        "is_correct": False,
    },
    {
        "id": "030",
        "scenario": "Assignment claim contradicts evidence",
        "claim": "Either party may freely assign their rights under this agreement without restriction.",
        "evidence_snippet": "Neither party may assign or transfer any of its rights or obligations hereunder without the prior written consent of the other party.",
        "critic_verdict": "unsupported",
        "nli_label": "contradict",
        "frac_supported": 0.00,
        "margin_norm": 0.40,
        "min_rerank": 0.40,
        "agreement": 0.00,
        "is_correct": False,
    },
]


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for case in CASES:
        raw = _raw(
            case["frac_supported"],
            case["margin_norm"],
            case["min_rerank"],
            case["agreement"],
        )
        output = {
            "raw_score": raw,
            "is_correct": case["is_correct"],
            "id": case["id"],
            "scenario": case["scenario"],
            "claim": case["claim"],
            "evidence_snippet": case["evidence_snippet"],
            "critic_verdict": case["critic_verdict"],
            "nli_label": case["nli_label"],
            "components": {
                "frac_supported": case["frac_supported"],
                "margin_norm": case["margin_norm"],
                "min_rerank": case["min_rerank"],
                "agreement": case["agreement"],
            },
        }
        path = OUT_DIR / f"case_{case['id']}.json"
        path.write_text(json.dumps(output, indent=2))
        print(f"  wrote {path.name}  raw={raw:.4f}  correct={case['is_correct']}")

    print(f"\n{len(CASES)} cases written to {OUT_DIR}")


if __name__ == "__main__":
    main()
