export const pricingPlans = [
  {
    id: "starter",
    name: "Starter",
    desc: "For personal projects",
    priceMonthly: 0,
    priceYearly: 0,
    features: [
      "50 document uploads",
      "AI Chat",
      "Citations",
      "Verification",
      "Basic Analytics",
    ],
    cta: "Start Free",
    popular: false,
    contactSales: false,
  },
  {
    id: "pro",
    name: "Pro",
    desc: "For professionals and small teams",
    priceMonthly: 19,
    priceYearly: 15,
    features: [
      "Unlimited documents",
      "Priority processing",
      "Collections",
      "Advanced AI Chat",
      "Evidence Explorer",
      "Citation Highlighting",
      "Trust Score",
      "Analytics",
      "Export",
      "API Access",
    ],
    cta: "Start Pro",
    popular: true,
    contactSales: false,
  },
  {
    id: "business",
    name: "Business",
    desc: "For growing organizations",
    priceMonthly: 79,
    priceYearly: 63,
    features: [
      "Everything in Pro",
      "Team Workspaces",
      "Role Permissions",
      "Shared Collections",
      "SSO",
      "Audit Logs",
      "Usage Analytics",
      "Higher API limits",
      "Priority Support",
    ],
    cta: "Upgrade to Business",
    popular: false,
    contactSales: false,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    desc: "For large scale deployments",
    priceMonthly: null, // Custom Pricing
    priceYearly: null,
    features: [
      "Unlimited Everything",
      "Dedicated Infrastructure",
      "SOC2",
      "Private Deployments",
      "Custom Integrations",
      "SLA",
      "Dedicated Support",
      "White-label",
    ],
    cta: "Book Demo",
    popular: false,
    contactSales: true,
  },
];

export const trustBadges = [
  "SOC2 Ready",
  "Encrypted Storage",
  "Workspace Isolation",
  "GDPR Ready",
  "Unlimited Scaling",
  "24/7 Monitoring",
];

export const comparisonFeatures = [
  {
    category: "Core Intelligence",
    features: [
      { name: "Document Uploads", starter: "50", pro: "Unlimited", business: "Unlimited", enterprise: "Unlimited" },
      { name: "Reasoning Pipeline", starter: "Basic", pro: "Advanced", business: "Advanced", enterprise: "Custom" },
      { name: "Hybrid Search", starter: true, pro: true, business: true, enterprise: true },
      { name: "Citation Highlighting", starter: false, pro: true, business: true, enterprise: true },
      { name: "Trust Score", starter: false, pro: true, business: true, enterprise: true },
      { name: "Abstention", starter: true, pro: true, business: true, enterprise: true },
    ]
  },
  {
    category: "Platform & Security",
    features: [
      { name: "API Access", starter: false, pro: true, business: true, enterprise: true },
      { name: "Rate Limits", starter: "Low", pro: "Medium", business: "High", enterprise: "Custom" },
      { name: "RBAC", starter: false, pro: false, business: true, enterprise: true },
      { name: "SSO (SAML)", starter: false, pro: false, business: true, enterprise: true },
      { name: "SOC2 Report", starter: false, pro: false, business: true, enterprise: true },
      { name: "VPC Peering", starter: false, pro: false, business: false, enterprise: true },
    ]
  },
  {
    category: "Support & SLAs",
    features: [
      { name: "Community", starter: true, pro: true, business: true, enterprise: true },
      { name: "Email", starter: false, pro: true, business: true, enterprise: true },
      { name: "Priority (24h)", starter: false, pro: false, business: true, enterprise: true },
      { name: "Dedicated Slack", starter: false, pro: false, business: false, enterprise: true },
      { name: "Custom SLA", starter: false, pro: false, business: false, enterprise: true },
    ]
  }
];

export const pricingFaqs = [
  {
    question: "Do you charge per user or per query?",
    answer: "Our Pro and Business plans include a generous baseline for both users and queries. You only pay overages if you significantly exceed these limits, ensuring your costs scale predictably with your actual usage rather than per-seat."
  },
  {
    question: "What happens if I exceed my document limit?",
    answer: "If you hit your document limit, you can continue to query existing documents without interruption. To upload new documents, you can either upgrade your plan or enable automatic pay-as-you-go overages in your billing settings."
  },
  {
    question: "Can I host Clarity on my own infrastructure?",
    answer: "Yes, our Enterprise plan supports completely isolated VPC deployments, on-premise installations, and dedicated single-tenant cloud environments. Contact our sales team to discuss your security requirements."
  },
  {
    question: "How do you calculate the Trust Score?",
    answer: "The Trust Score is a composite metric generated by our proprietary cross-check pipeline. It evaluates the semantic density of the retrieved chunks, the hallucination probability from the LLM, and explicitly verifies the generated answer against the source text before returning it to the user."
  },
  {
    question: "Is there a free trial?",
    answer: "Yes! You can start using the Starter plan for free indefinitely with up to 50 documents. For Pro features, you can activate a 14-day free trial directly from the dashboard."
  },
  {
    question: "Do you train AI models on my private data?",
    answer: "Absolutely not. Clarity is built on a zero-trust architecture. We never use your proprietary documents, queries, or results to train foundational models. Your data is encrypted at rest and in transit."
  },
  {
    question: "What document formats does the pipeline support?",
    answer: "Our vision-based OCR engine natively processes complex PDFs (including scanned documents), Microsoft Word (.docx), Excel (.xlsx), and raw images (PNG/JPEG). It preserves layout, tables, and nested structures."
  },
  {
    question: "How easy is it to integrate into our existing app?",
    answer: "Very easy. We provide fully typed SDKs for Node.js, Python, and Go, along with a comprehensive REST API. You can bypass the UI and directly stream verified answers and citations into your own product."
  }
];
